### ISSUE TITLE
Adapting to a different language

### ISSUE THREAD

**Issue by hasnhasan** [lrojas12/lstm-sentence-generator#2]
How can I train in a different language?

**Comment by luisarojas** [comment]
You would need to train with data that is in the language of your choice. I trained with "Twelve Short Mystery Stories" from [Project Gutenberg](http://gutenberg.ca/).
You can also check out my [report on the project](https://github.com/luisarojas/lstm-sentence-generator/blob/master/report.pdf) for more detailed information.
